apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-api
  namespace: inventory
  annotations:
    # Replace YOUR_PROJECT_ID after Terraform apply
    iam.gke.io/gcp-service-account: inventory-api@YOUR_PROJECT_ID.iam.gserviceaccount.com
