apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-api
  namespace: inventory-staging
  annotations:
    iam.gke.io/gcp-service-account: inventory-api-staging@YOUR_PROJECT_ID.iam.gserviceaccount.com
